-- Seed calculator/syllabus profiles for the five AITU courses already present in the
-- supplied study dashboard. Existing calculator state is deliberately preserved.

with calculator_profiles(code, profile) as (
values
  ('OS52-EN', '{"definition": {"version": 1, "sourceName": "AITU study profile from supplied schedule/calculator HTML", "attestationThreshold": 25, "fields": [{"id": "os-a1", "label": "Lab 1 (Week 1)", "period": "att1", "weightPercent": 20}, {"id": "os-a2", "label": "Lab 2 (Week 2)", "period": "att1", "weightPercent": 20}, {"id": "os-a3", "label": "Lab 3 (Week 3)", "period": "att1", "weightPercent": 20}, {"id": "os-a4", "label": "Lab 4 (Week 4)", "period": "att1", "weightPercent": 20}, {"id": "os-mid", "label": "Midterm Exam", "period": "att1", "weightPercent": 20}, {"id": "os-a5", "label": "Lab 5 (Week 6)", "period": "att2", "weightPercent": 20}, {"id": "os-a6", "label": "Lab 6 (Week 7)", "period": "att2", "weightPercent": 20}, {"id": "os-a7", "label": "Lab 7 (Week 8)", "period": "att2", "weightPercent": 20}, {"id": "os-a8", "label": "Lab 8 (Week 9)", "period": "att2", "weightPercent": 20}, {"id": "os-end", "label": "Endterm Exam", "period": "att2", "weightPercent": 20}, {"id": "os-exam", "label": "Экзамен", "period": "exam", "weightPercent": 100}]}, "values": {"os-a1": null, "os-a2": null, "os-a3": null, "os-a4": null, "os-mid": null, "os-a5": null, "os-a6": null, "os-a7": null, "os-a8": null, "os-end": null, "os-exam": null}, "target": 70}'::jsonb),
  ('DMS52-EN', '{"definition": {"version": 1, "sourceName": "AITU study profile from supplied schedule/calculator HTML", "attestationThreshold": 25, "fields": [{"id": "dms-a1", "label": "Assignment 1: ERD Diagram", "period": "att1", "weightPercent": 20}, {"id": "dms-a2", "label": "Assignment 2: Intro to DDL", "period": "att1", "weightPercent": 20}, {"id": "dms-a3", "label": "Assignment 3: DML & JOINs", "period": "att1", "weightPercent": 20}, {"id": "dms-q1", "label": "Learn Quiz (Moodle)", "period": "att1", "weightPercent": 10}, {"id": "dms-mid", "label": "Midterm Exam (Mixed)", "period": "att1", "weightPercent": 30}, {"id": "dms-a4", "label": "Assignment 4: Subqueries", "period": "att2", "weightPercent": 20}, {"id": "dms-a5", "label": "Assignment 5: Window Functions", "period": "att2", "weightPercent": 20}, {"id": "dms-a6", "label": "Assignment 6: Set Ops & ACID", "period": "att2", "weightPercent": 20}, {"id": "dms-q2", "label": "Learn Quiz (Moodle)", "period": "att2", "weightPercent": 10}, {"id": "dms-end", "label": "Endterm Exam (Mixed)", "period": "att2", "weightPercent": 30}, {"id": "dms-exam", "label": "Экзамен", "period": "exam", "weightPercent": 100}]}, "values": {"dms-a1": null, "dms-a2": null, "dms-a3": null, "dms-q1": null, "dms-mid": null, "dms-a4": null, "dms-a5": null, "dms-a6": null, "dms-q2": null, "dms-end": null, "dms-exam": null}, "target": 70}'::jsonb),
  ('K(RUSSIAN)L51-RU', '{"definition": {"version": 1, "sourceName": "AITU study profile from supplied schedule/calculator HTML", "attestationThreshold": 25, "fields": [{"id": "krl-a1", "label": "Задание 1: Анализ языковых норм (Неделя 4)", "period": "att1", "weightPercent": 60}, {"id": "krl-mid", "label": "Midterm Exam (Тестирование)", "period": "att1", "weightPercent": 40}, {"id": "krl-a2", "label": "Задание 2: Презентация «Оратор» (Недели 8-9)", "period": "att2", "weightPercent": 60}, {"id": "krl-end", "label": "Endterm Exam (Тестирование)", "period": "att2", "weightPercent": 40}, {"id": "krl-exam", "label": "Экзамен", "period": "exam", "weightPercent": 100}]}, "values": {"krl-a1": null, "krl-mid": null, "krl-a2": null, "krl-end": null, "krl-exam": null}, "target": 70}'::jsonb),
  ('CNC53-EN', '{"definition": {"version": 1, "sourceName": "AITU study profile from supplied schedule/calculator HTML", "attestationThreshold": 25, "fields": [{"id": "cnc-p1", "label": "Практики / лабораторные", "period": "att1", "weightPercent": 60}, {"id": "cnc-mid", "label": "Midterm Exam", "period": "att1", "weightPercent": 40}, {"id": "cnc-p2", "label": "Практики / лабораторные", "period": "att2", "weightPercent": 60}, {"id": "cnc-end", "label": "Endterm Exam", "period": "att2", "weightPercent": 40}, {"id": "cnc-exam", "label": "Экзамен", "period": "exam", "weightPercent": 100}]}, "values": {"cnc-p1": null, "cnc-mid": null, "cnc-p2": null, "cnc-end": null, "cnc-exam": null}, "target": 70}'::jsonb),
  ('DLD52-EN', '{"definition": {"version": 1, "sourceName": "AITU study profile from supplied schedule/calculator HTML", "attestationThreshold": 25, "fields": [{"id": "dld-p1", "label": "Практики / лабораторные", "period": "att1", "weightPercent": 60}, {"id": "dld-mid", "label": "Midterm Exam", "period": "att1", "weightPercent": 40}, {"id": "dld-p2", "label": "Практики / лабораторные", "period": "att2", "weightPercent": 60}, {"id": "dld-end", "label": "Endterm Exam", "period": "att2", "weightPercent": 40}, {"id": "dld-exam", "label": "Экзамен", "period": "exam", "weightPercent": 100}]}, "values": {"dld-p1": null, "dld-mid": null, "dld-p2": null, "dld-end": null, "dld-exam": null}, "target": 70}'::jsonb)
)
update public.study_courses as course
set metadata = jsonb_set(
  coalesce(course.metadata, '{}'::jsonb),
  '{study_calculator_v1}',
  profile.profile,
  true
)
from calculator_profiles as profile
where course.code = profile.code
  and course.status = 'active'
  and not (coalesce(course.metadata, '{}'::jsonb) ? 'study_calculator_v1');
